[versions]
kotlin = "1.8.10"
kotlin-inject = "0.6.1"
ksp = "1.8.10-1.0.9"

plugin-android-gradle = "7.4.2"

[libraries]
tatarka-kotlin-inject = { module = "me.tatarka.inject:kotlin-inject-runtime", version.ref = "kotlin-inject" }
tatarka-kotlin-inject-compiler = { module = "me.tatarka.inject:kotlin-inject-compiler-ksp", version.ref = "kotlin-inject" }

[bundles]

[plugins]
android-application = { id = "com.android.application", version.ref = "plugin-android-gradle" }
android-library = { id = "com.android.library", version.ref = "plugin-android-gradle" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

jetbrains-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }