package uk.co.harnick.troupetent.core.ui.theme.presentation
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(color = 0xFF00677F)
val md_theme_light_onPrimary = Color(color = 0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(color = 0xFFB7EAFF)
val md_theme_light_onPrimaryContainer = Color(color = 0xFF001F28)
val md_theme_light_secondary = Color(color = 0xFF006876)
val md_theme_light_onSecondary = Color(color = 0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(color = 0xFF9FEFFF)
val md_theme_light_onSecondaryContainer = Color(color = 0xFF001F25)
val md_theme_light_tertiary = Color(color = 0xFF5A5C7E)
val md_theme_light_onTertiary = Color(color = 0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(color = 0xFFE1E0FF)
val md_theme_light_onTertiaryContainer = Color(color = 0xFF171837)
val md_theme_light_error = Color(color = 0xFFFE5F55)
val md_theme_light_errorContainer = Color(color = 0xFFFFEFEE)
val md_theme_light_onError = Color(color = 0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(color = 0xFF410002)
val md_theme_light_background = Color(color = 0xFFF3FEFF)
val md_theme_light_onBackground = Color(color = 0xFF002022)
val md_theme_light_surface = Color(color = 0xFFF3FEFF)
val md_theme_light_onSurface = Color(color = 0xFF002022)
val md_theme_light_surfaceVariant = Color(color = 0xFFDBE4E8)
val md_theme_light_onSurfaceVariant = Color(color = 0xFF40484C)
val md_theme_light_outline = Color(color = 0xFF70787C)
val md_theme_light_inverseOnSurface = Color(color = 0xFFC3FBFF)
val md_theme_light_inverseSurface = Color(color = 0xFF00373A)
val md_theme_light_inversePrimary = Color(color = 0xFF5DD5FB)
val md_theme_light_shadow = Color(color = 0xFF000000)
val md_theme_light_surfaceTint = Color(color = 0xFF00677F)
val md_theme_light_outlineVariant = Color(color = 0xFFBFC8CC)
val md_theme_light_scrim = Color(color = 0xFF000000)

val md_theme_dark_primary = Color(color = 0xFF5DD5FB)
val md_theme_dark_onPrimary = Color(color = 0xFF003543)
val md_theme_dark_primaryContainer = Color(color = 0xFF004E61)
val md_theme_dark_onPrimaryContainer = Color(color = 0xFFB7EAFF)
val md_theme_dark_secondary = Color(color = 0xFF51D7EE)
val md_theme_dark_onSecondary = Color(color = 0xFF00363E)
val md_theme_dark_secondaryContainer = Color(color = 0xFF004E59)
val md_theme_dark_onSecondaryContainer = Color(color = 0xFF9FEFFF)
val md_theme_dark_tertiary = Color(color = 0xFFC3C3EB)
val md_theme_dark_onTertiary = Color(color = 0xFF2C2E4D)
val md_theme_dark_tertiaryContainer = Color(color = 0xFF424465)
val md_theme_dark_onTertiaryContainer = Color(color = 0xFFE1E0FF)
val md_theme_dark_error = Color(color = 0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(color = 0xFF93000A)
val md_theme_dark_onError = Color(color = 0xFF690005)
val md_theme_dark_onErrorContainer = Color(color = 0xFFFFDAD6)
val md_theme_dark_background = Color(color = 0xFF002022)
val md_theme_dark_onBackground = Color(color = 0xFF70F5FF)
val md_theme_dark_surface = Color(color = 0xFF002022)
val md_theme_dark_onSurface = Color(color = 0xFF70F5FF)
val md_theme_dark_surfaceVariant = Color(color = 0xFF40484C)
val md_theme_dark_onSurfaceVariant = Color(color = 0xFFBFC8CC)
val md_theme_dark_outline = Color(color = 0xFF8A9296)
val md_theme_dark_inverseOnSurface = Color(color = 0xFF002022)
val md_theme_dark_inverseSurface = Color(color = 0xFF70F5FF)
val md_theme_dark_inversePrimary = Color(color = 0xFF00677F)
val md_theme_dark_shadow = Color(color = 0xFF000000)
val md_theme_dark_surfaceTint = Color(color = 0xFF5DD5FB)
val md_theme_dark_outlineVariant = Color(color = 0xFF40484C)
val md_theme_dark_scrim = Color(color = 0xFF000000)


val seed = Color(color = 0xFF1DA0C3)
